CREATE DATABASE IF NOT EXISTS naap_parking;
USE naap_parking;

CREATE TABLE IF NOT EXISTS students (
  id INT PRIMARY KEY AUTO_INCREMENT,
  student_number VARCHAR(50) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  program VARCHAR(120),
  email VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicles (
  id INT PRIMARY KEY AUTO_INCREMENT,
  student_id INT NOT NULL,
  plate_number VARCHAR(30) NOT NULL UNIQUE,
  model VARCHAR(120),
  color VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vehicle_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stickers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id INT NOT NULL,
  sticker_code VARCHAR(60) NOT NULL UNIQUE,
  qr_token VARCHAR(80) NOT NULL UNIQUE,
  status ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
  issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sticker_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS scan_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sticker_id INT NULL,
  scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  result ENUM('VALID', 'INVALID', 'REVOKED', 'EXPIRED') NOT NULL,
  action ENUM('ENTRY', 'EXIT', 'VERIFY') NOT NULL DEFAULT 'VERIFY',
  gate VARCHAR(80),
  notes VARCHAR(255),
  CONSTRAINT fk_scan_sticker FOREIGN KEY (sticker_id) REFERENCES stickers(id) ON DELETE SET NULL
);
